version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gmao3
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./test1
      dockerfile: Dockerfile
    container_name: django_backend
    command: ["gunicorn", "e.e.wsgi:application", "--bind", "0.0.0.0:8000"]
    volumes:
      - ./test1:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - PYTHONPATH=/app  # Add this line

  frontend:
    build:
      context: ./frontendgmao/gmao
    container_name: react_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  db_data:
