# Stage 1: Build the React application
FROM node:14 AS build

# Set the working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY src/package*.json ./
RUN npm install

# Copy the rest of the application code
COPY src/ .

# Build the React application
RUN npm run build

# Stage 2: Serve the React application using nginx

CMD ["npm", "start"]
