# Generated by Django 5.0.1 on 2024-02-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gestionmaitenace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervention', models.IntegerField(max_length=200)),
                ('date_intervention', models.DateField()),
                ('dure', models.IntegerField(max_length=200)),
                ('metrie', models.CharField(choices=[('1', 'ing'), ('2', 'sec'), ('3', 'admin')], default='1', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('phone', models.IntegerField(max_length=200)),
                ('adresse', models.CharField(max_length=200)),
                ('mail', models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('phone', models.IntegerField(max_length=200)),
                ('adresse', models.CharField(max_length=200)),
                ('mail', models.EmailField(max_length=200)),
            ],
        ),
    ]
