# Generated by Django 5.0.1 on 2024-07-15 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_enterprise_alter_enatte_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.enterprise'),
        ),
        migrations.AddField(
            model_name='interven',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.enterprise'),
        ),
    ]
