# Generated by Django 5.0.1 on 2024-07-15 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_customuser_enterprise_interven_enterprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.enterprise'),
        ),
    ]
