# Generated by Django 5.0.1 on 2024-02-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_customuser_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_citoyen',
            field=models.BooleanField(default=False, verbose_name='directeur'),
        ),
    ]
