# Generated by Django 5.0.1 on 2024-02-29 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_customuser_is_citoyen'),
    ]

    operations = [
        migrations.CreateModel(
            name='intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=2048)),
                ('date_creation', models.DateField(default=datetime.datetime(2024, 2, 29, 11, 3, 13, 73622))),
                ('date_debut', models.DateField(default='')),
                ('date_fin', models.DateField(default='')),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_citoyen',
            field=models.BooleanField(default=False, verbose_name='citoyen'),
        ),
    ]
