# Generated by Django 5.0.1 on 2024-02-29 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_intervention_alter_customuser_is_citoyen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='date_creation',
            field=models.DateField(default=datetime.datetime(2024, 2, 29, 11, 18, 10, 395830)),
        ),
    ]
