# Generated by Django 5.0.1 on 2024-02-29 10:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_intervention_date_creation'),
    ]

    operations = [
        migrations.CreateModel(
            name='interventions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=2048)),
                ('date_creation', models.DateField(default=datetime.datetime(2024, 2, 29, 11, 19, 11, 814200))),
                ('date_debut', models.DateField(default='')),
                ('date_fin', models.DateField(default='')),
            ],
        ),
        migrations.DeleteModel(
            name='intervention',
        ),
    ]
