# Generated by Django 5.0.1 on 2024-02-29 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_interventions_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interventions',
            name='date_creation',
            field=models.DateField(default=datetime.datetime(2024, 2, 29, 12, 19, 20, 478826)),
        ),
        migrations.AlterField(
            model_name='interventions',
            name='date_debut',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='interventions',
            name='date_fin',
            field=models.DateField(),
        ),
    ]
