# Generated by Django 5.0.1 on 2024-02-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_interventions_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interventions',
            name='date_creation',
            field=models.DateField(),
        ),
    ]
