# Generated by Django 5.0.1 on 2024-02-29 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_interventions_date_creation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='interventions',
            new_name='interven',
        ),
    ]
