# Generated by Django 5.0.1 on 2024-02-29 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_rename_interventions_interven'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interven',
            name='date_creation',
            field=models.DateField(default=datetime.date(2024, 2, 29)),
        ),
    ]
