# Generated by Django 5.0.1 on 2024-06-25 21:52

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_customuser_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('telephone', models.IntegerField(max_length=100)),
                ('sujet_type', models.CharField(choices=[('probleme avec compte ', 'probleme avec compte '), ('publicite', 'publicite '), ('suggestion', 'sugestion'), ('autre', 'auttre'), ('abonement', 'abonement')], default='autre', max_length=1100)),
                ('message', models.TextField(max_length=2500)),
            ],
        ),
        migrations.CreateModel(
            name='enatte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_de_creation', models.DateField(default=datetime.date(2024, 6, 25))),
            ],
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, null=True)),
                ('marque', models.CharField(max_length=100, null=True)),
                ('prix', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('date_ajout', models.DateField(auto_now_add=True)),
                ('statut', models.BooleanField(default=True)),
                ('numero_serie', models.CharField(blank=True, max_length=100)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('caracteristiques_techniques', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('descrtions', models.TextField(max_length=3000)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='adresse',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_de_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='interven',
            name='adresse',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='adresse '),
        ),
        migrations.AddField(
            model_name='interven',
            name='citoyen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interven',
            name='etat',
            field=models.CharField(choices=[('Nouveau', 'Nouveau'), ('En attente', 'En attente'), ('En cours', 'En cours'), ('Assigné', 'Assigné'), ('Terminé', 'Terminé'), ('Annulé', 'Annulé'), ('Clôture', 'Clôture')], default='Nouveau', max_length=200),
        ),
        migrations.AddField(
            model_name='interven',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='interven',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='interven',
            name='technicien',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interven',
            name='titre',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='titre'),
        ),
        migrations.AlterField(
            model_name='interven',
            name='date_creation',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='interven',
            name='date_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interven',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='converstation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('participants', models.ManyToManyField(related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='interven',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.converstation'),
        ),
        migrations.AddField(
            model_name='interven',
            name='raison',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.enatte'),
        ),
        migrations.AddField(
            model_name='interven',
            name='equipements',
            field=models.ManyToManyField(blank=True, to='myapp.equipement'),
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('horodatage', models.DateTimeField(auto_now_add=True)),
                ('message_type', models.CharField(choices=[('private', 'Message privé'), ('public', 'Message public')], default='private', max_length=10)),
                ('converstation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.converstation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rapport', models.DateField(auto_now_add=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('interventions', models.ManyToManyField(blank=True, null=True, to='myapp.interven')),
            ],
        ),
        migrations.AddField(
            model_name='equipement',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.service'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.service'),
        ),
        migrations.AddField(
            model_name='interven',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.service'),
        ),
    ]
