# Generated by Django 5.0.1 on 2024-06-25 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_contact_enatte_equipement_service_customuser_adresse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enatte',
            name='date_de_creation',
            field=models.DateField(default=datetime.datetime(2024, 6, 25, 22, 56, 6, 470026)),
        ),
    ]
