# Generated by Django 5.0.1 on 2024-06-28 19:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_enatte_date_de_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enatte',
            name='date_de_creation',
            field=models.DateField(default=datetime.datetime(2024, 6, 28, 20, 59, 38, 597880)),
        ),
    ]
