# Generated by Django 5.0.1 on 2024-06-28 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_enatte_date_de_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enatte',
            name='date_de_creation',
            field=models.DateField(default=datetime.datetime(2024, 6, 28, 21, 2, 45, 279632)),
        ),
    ]
