# Generated by Django 5.0.1 on 2024-06-28 20:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_enatte_date_de_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enatte',
            name='date_de_creation',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
