# Dockerfile for React
FROM node:14

# Set the working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the React application
RUN npm run build

# Serve the React application
RUN npm install -g serve
CMD ["serve", "-s", "npm start "]
